namespace NmeLib.Jumps
{
    public enum Ease
    {
        LinearIn,
        LinearOut,
        LinearInOut,
        LinearOutIn,
        ExpIn,
        ExpOut,
        ExpInOut,
        ExpOutIn,
        AccIn,
        AccOut,
        AccInOut,
        AccOutIn,
        CircIn,
        CircOut,
        CircInOut,
        CircOutIn,
        ElasticIntoPlace,
        BounceOnce,
        OvershootOnce,
        Punch,
        PunchElastic,
        SmoothIn,
        SmoothOut,
        SmoothInOut,
        SmoothOutIn
    }
}